[REVIEW] FEA Add support for retrying docker pulls on failure
gpuopenanalytics/remote-docker-plugin pull request #40
Opened 2020-10-22 21:16 UTC by dillon-cullinan

# Summary

* Replaced `forcePull` jelly block with an optionalBlock with an encapsulated `maxRetries` field
* Added `ForcePull` class and accompanying constructor that reads the input
* `DockerImageConfiguration` constructor has been updated to use the new `ForcePull` class
* Added a loop that retries the `docker pull` command based on `maxRetries` field

# Testing Screenshots

Note: In the examples with retries, I had it hardcoded to "Fail" the docker pull to force the retries to happen, you can see in the console output that the images are downloaded/up-to-date.

**Force Pull Off**
<img width="1240" alt="Screen Shot 2020-10-22 at 4 59 39 PM" src="https://user-images.githubusercontent.com/18494947/96929671-7cfd1280-1488-11eb-9b02-dd7170afc4cf.png">

**Force Pull On : Retries = 0**

<img width="1521" alt="Screen Shot 2020-10-22 at 5 06 42 PM" src="https://user-images.githubusercontent.com/18494947/96929972-fac11e00-1488-11eb-9a92-d6aeea34c7c2.png">

**Force Pull On : Retries = 5**

<img width="1491" alt="Screen Shot 2020-10-22 at 5 07 44 PM" src="https://user-images.githubusercontent.com/18494947/96930088-25ab7200-1489-11eb-8ef5-5173a551226f.png">

**Invalid Input Errors**

<img width="1657" alt="Screen Shot 2020-10-22 at 5 08 42 PM" src="https://user-images.githubusercontent.com/18494947/96930148-41af1380-1489-11eb-836c-07b917d62834.png">

<img width="1651" alt="Screen Shot 2020-10-22 at 5 09 46 PM" src="https://user-images.githubusercontent.com/18494947/96930257-67d4b380-1489-11eb-8fcf-70127d51f22d.png">

**Successful Pull : Retries = 3 (Removed hardcoded failure)**

<img width="1341" alt="Screen Shot 2020-10-22 at 5 11 56 PM" src="https://user-images.githubusercontent.com/18494947/96930448-b5512080-1489-11eb-88d9-c20cd61b815f.png">

2020-10-22 21:16 UTC, GPUtester commented
Can one of the admins verify this patch?

2020-10-23 01:03 UTC, raydouglass requested changes

2020-10-23 01:03 UTC, raydouglass commented on src/main/java/com/gpuopenanalytics/jenkins/remotedocker/job/DockerImageConfiguration.java
> +                                    ForcePull forcePull) {
Doing it this way will break existing job configurations when the plugin is updated. The constructor should take two parameters `forcePull` and `maxRetries` and the jelly should bind to those.

2020-10-23 01:04 UTC, raydouglass requested changes

2020-10-23 01:04 UTC, raydouglass commented on src/main/java/com/gpuopenanalytics/jenkins/remotedocker/job/DockerImageConfiguration.java
> +                launcher.getListener().getLogger().println("Docker pull failed, retrying...");
It would be nice if the message said like `retrying 2 of 3` etc

2020-10-30 16:40 UTC, raydouglass approved these changes

2020-10-30 16:40 UTC, merged